name: agrimind
description: "Topraksız Tarım Otomasyon AI"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # İkonlar
  cupertino_icons: ^1.0.2

  # Fontlar (Eski http ile uyumlu sürüme çektik)
  google_fonts: ^4.0.4
  intl: ^0.18.1 # intl paketi eklendi
  provider: ^6.0.5 # provider paketi eklendi

  # Grafikler & İletişim
  fl_chart: ^1.1.1
  mqtt_client: ^10.11.3

  # Kamera ve Http (Ayrılmaz ikili)
  flutter_mjpeg: ^2.0.4
  http: ^0.13.6
  flutter_joystick: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# --- SİHİRLİ KISIM BURASI (En Alta Ekle) ---
# Bu kısım, mjpeg paketini zorla yeni http ile çalıştırır.
